[package]
name = "tq2-hc-revival"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"
description = "Titan Quest 2 characters revive dead Hardcore characters"
authors = ["hexqnt <hexqntlab@gmail.com>"]
repository = "https://github.com/hexqnt/tq2-hc-revival"

[dependencies]
clap = { version = "4.6", default-features = false, features = ["derive", "std", "help", "usage", "error-context"] }
colored = "3.1"
comfy-table = { version = "8.0", default-features = false, features = ["tty"] }
time = { version = "0.3", features = ["formatting", "local-offset", "macros"] }

[profile.release]
strip = true
panic = "abort"
opt-level = 3
lto = true
codegen-units = 1
incremental = false

[profile.size-analysis]
inherits = "release"
strip = false
debug = 1
